# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Create directories
      run: mkdir -p ./app
    - name: Decode google-services.json
      run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > ./app/google-services.json
    - name: Upload google-services.json
      uses: actions/upload-artifact@v2
      with:
        name: google-services
        path: ./app/google-services.json

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: actions/checkout@v3
    - name: Download google-services.json
      uses: actions/download-artifact@v2
      with:
        name: google-services
        path: ./app
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: actions/checkout@v3
    - name: Download google-services.json
      uses: actions/download-artifact@v2
      with:
        name: google-services
        path: ./app
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: app/build/reports/tests/testDebugUnitTest
